# Base image
FROM ubuntu:22.04 AS base
ARG VERSION=0.6.4.post1
ENV CCACHE_DIR=/root/.cache/ccache
ENV CMAKE_CXX_COMPILER_LAUNCHER=ccache
ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:/usr/local/lib/libiomp5.so"


# Python environment setup
FROM base AS python-env
RUN python3 -m pip install --upgrade pip && \
    pip install virtualenv && \
    virtualenv /opt/vllm-venv

# Activate virtual environment in Docker image
ENV PATH="/opt/vllm-venv/bin:$PATH"

# Code preparation
FROM python-env AS code-prep
WORKDIR /workspace
RUN git clone https://github.com/vllm-project/vllm.git && cd vllm && git checkout v${VERSION}

# Code building stage
FROM code-prep AS builder
# Install build dependencies and clean up in one layer to reduce image size
RUN apt-get update -y \
    && apt-get install -y curl ccache git wget vim numactl gcc-12 g++-12 python3 python3-pip libtcmalloc-minimal4 libnuma-dev ffmpeg libsm6 libxext6 libgl1 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo 'ulimit -c 0' >> ~/.bashrc

WORKDIR /workspace/vllm
COPY cmake/cpu_extension.cmake .
RUN sed -i 's/if (AVX512_FOUND AND NOT AVX512_DISABLED)/if (AVX512_FOUND OR AVX2_FOUND)/' cmake/cpu_extension.cmake \
    && cat cmake/cpu_extension.cmake

ARG PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
RUN pip install -r requirements-build.txt \
    && pip install -v -r requirements-cpu.txt \
    && VLLM_TARGET_DEVICE=cpu python3 setup.py bdist_wheel \
    && pip install dist/*.whl

# Final image
FROM base AS final
COPY --from=builder /opt/vllm-venv /opt/vllm-venv

# Activate virtual environment in Docker image
ENV PATH="/opt/vllm-venv/bin:$PATH"

WORKDIR /workspace
ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]