ARG VERSION=v0.6.3
ARG CUDA_VERSION=12.4.1
ARG PYTHON_VERSION=3.12
FROM nvidia/cuda:${CUDA_VERSION}-cudnn-runtime-ubuntu22.04
ENV PORT 8080
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install flashinfer -i https://flashinfer.ai/whl/cu124/torch2.4/
RUN pip3 install vllm==${VERSION}

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
